### ISSUE TITLE
Async events

### ISSUE THREAD

**Issue by wolfen351** [upta/pubsub#19]
How do we handle the case in which the event handler needs to be async?

**Comment by upta** [comment]
Honestly the library was built before such things became a serious consideration :)  As a work around, you probably just use the old-school .ContinueWith on your task inside your event handler.

I'll try to take a look at the project this weekend and see if there is a straight-forward way I can add some modern async niceties

**Comment by wolfen351** [comment]
That would be really nice! Thanks! :) 

For the moment I wrapped the method into force-sync using Nito.AsyncEx package, but it would be great if this supported async out the box, at least at the subscribe level..

**Comment by upta** [comment]
Alrighty, worked on this a bit this morning and pushed some changes into the "async-test" branch for you to check out and see if they work in your situation (all the unit tests are passing, but I'd like to get some real-world confirmation as well before updating Nuget).

Subscribe now has an overload accept a Task-returning Func

![image](https://user-images.githubusercontent.com/3310732/51444735-548f2580-1cb0-11e9-998b-6199fa498eb9.png)

And Publish now returns a Task. 

_Note_: this will cause some green warnings in existing code (since you're going to be doing a fire-and-forget on an async now without doing something with the Task it returns).

![image](https://user-images.githubusercontent.com/3310732/51444772-e39c3d80-1cb0-11e9-8d05-95097ee9a47b.png)

I opted for this route instead of making, say, a PublishAsync as I thought that would simply be confusing (since it isn't _only_ firing the async handlers, but all of them) and muddy the interface.

If you want to get rid of the warning, you can simply assign the Task to a variable:

![image](https://user-images.githubusercontent.com/3310732/51444780-03336600-1cb1-11e9-902a-583086457cfb.png)

Or, in C# 7.0+ you can use a discard:

![image](https://user-images.githubusercontent.com/3310732/51444786-1cd4ad80-1cb1-11e9-848c-669a998fb7c7.png)

**Comment by upta** [comment]
@wolfen351 Where you able to check out the new branch and see if it worked for you?

**Comment by upta** [comment]
@wolfen351 Still something you're looking for? ;)

**Comment by wolfen351** [comment]
Nope, the changes work perfectly, thanks!

**Comment by upta** [comment]
Cool, I'll see about getting it merged into master and published out to nuget before long here.

Thanks!
